#!/usr/bin/env ruby

require_relative '../gems/bundler/setup'

lib_dir = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift lib_dir unless $LOAD_PATH.include?(lib_dir)

require 'error_telemetry_component'

require 'component_host'

ComponentHost.start('error-telemetry-component') do |host|
  host.register(ErrorTelemetryComponent::Start)
end
